### Импортирование библиотек

In [1]:
import pandas as pd
import numpy as np

### Загрузка подготовленных данных

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Создание целевой колонки

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Коммент

In [6]:
targets.sum() / targets.shape[0]
#Проверка на сбалансированность данных

0.45571428571428574

### Checkpoint

In [7]:
# data_with_targets = data_preprocessed.drop('Absenteeism Time in Hours', axis=1)
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 
                                           'Distance to Work', 'Day of the Week',
                                           'Daily Work Load Average'], axis=1)
#На основании коэффициентов, вычесленных далее, принято решение об удалении еще 'Distance to Work', 'Day_of_the_week',
#'Daily Work Load Average'

In [8]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Подбор входных параметров

In [9]:
data_with_targets.shape

(700, 12)

In [10]:
data_with_targets.iloc[:, :-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [11]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

### Стандартизация данных

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
        
        
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [13]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [14]:
colums_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']
columns_to_scale = [i for i in unscaled_inputs.columns.values if i not in colums_to_omit]
columns_to_scale

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets']

In [15]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [16]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\volon\anaconda3\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [17]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [18]:
scaled_inputs.shape

(700, 11)

### Разделение выборки

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train, x_valid, y_train, y_valid = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state=20)
print(x_train.shape, x_valid.shape, y_train.shape, y_valid.shape)

(560, 11) (140, 11) (560,) (140,)


### Модель

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [22]:
reg = LogisticRegression()

In [23]:
reg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
reg.score(x_train, y_train)

0.775

### Ручная проверка точности и создание резюмирующей таблицы

In [25]:
model_outputs = reg.predict(x_train)

In [26]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.775

In [27]:
reg.coef_

array([[ 2.78546935,  0.94941093,  3.02370596,  0.81642209,  0.15482395,
         0.60530699, -0.17125984,  0.28060346, -0.23399394,  0.34763672,
        -0.27255583]])

In [28]:
reg.intercept_

array([-1.6255675])

In [29]:
feature_name = unscaled_inputs.columns.values

In [30]:
summary_table = pd.DataFrame(columns=['Feature name'], data=feature_name)

In [31]:
summary_table['Coefficients'] = np.transpose(reg.coef_)

In [32]:
summary_table

Feature name  Coefficients
0                 Reason_1      2.785469
1                 Reason_2      0.949411
2                 Reason_3      3.023706
3                 Reason_4      0.816422
4              Month Value      0.154824
5   Transportation Expense      0.605307
6                      Age     -0.171260
7          Body Mass Index      0.280603
8                Education     -0.233994
9                 Children      0.347637
10                    Pets     -0.272556

In [33]:
summary_table.index = summary_table.index + 1

In [34]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficients
0                Intercept     -1.625568
1                 Reason_1      2.785469
2                 Reason_2      0.949411
3                 Reason_3      3.023706
4                 Reason_4      0.816422
5              Month Value      0.154824
6   Transportation Expense      0.605307
7                      Age     -0.171260
8          Body Mass Index      0.280603
9                Education     -0.233994
10                Children      0.347637
11                    Pets     -0.272556

In [35]:
summary_table['Odds ratio'] = np.exp(summary_table.Coefficients)
summary_table.sort_values('Odds ratio', ascending=False)

Feature name  Coefficients  Odds ratio
3                 Reason_3      3.023706   20.567372
1                 Reason_1      2.785469   16.207423
2                 Reason_2      0.949411    2.584187
4                 Reason_4      0.816422    2.262391
6   Transportation Expense      0.605307    1.831814
10                Children      0.347637    1.415718
8          Body Mass Index      0.280603    1.323929
5              Month Value      0.154824    1.167452
7                      Age     -0.171260    0.842603
9                Education     -0.233994    0.791367
11                    Pets     -0.272556    0.761431
0                Intercept     -1.625568    0.196800

### Тестирование модели

In [36]:
reg.score(x_valid, y_valid)

0.75

In [37]:
predict_proba = reg.predict_proba(x_valid)
predict_proba[:,1]

array([0.28496903, 0.41189893, 0.55774976, 0.21864579, 0.91599038,
       0.66718303, 0.70260689, 0.86105376, 0.21582977, 0.25034738,
       0.50899607, 0.77497612, 0.92376942, 0.26458356, 0.67482011,
       0.44735206, 0.45387385, 0.46485134, 0.59950991, 0.94247816,
       0.29983192, 0.21864579, 0.57951051, 0.57951051, 0.74072863,
       0.255571  , 0.488355  , 0.13950599, 0.89126816, 0.21864579,
       0.36983239, 0.68294059, 0.68651558, 0.53105889, 0.21864579,
       0.53669054, 0.22340507, 0.72374548, 0.40535194, 0.60348977,
       0.211188  , 0.44918058, 0.23911734, 0.40217883, 0.8286886 ,
       0.55116298, 0.69280974, 0.28496903, 0.21923206, 0.20391819,
       0.57010008, 0.32775181, 0.66718303, 0.2679743 , 0.83381729,
       0.43346857, 0.87847307, 0.23148182, 0.33787125, 0.34783002,
       0.6956413 , 0.65729614, 0.29099913, 0.78087589, 0.20910587,
       0.26730232, 0.08836837, 0.22340507, 0.71852092, 0.30038511,
       0.22340507, 0.29383053, 0.9042431 , 0.45953987, 0.60162

### Сохранение модели

In [38]:
import pickle

In [39]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [40]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)